
# Framework Paper Figures
# built from 20170905_thirtyk.R

#### OUTPUT: Figures for paper

#### LIBRARY DEPENDENCIES:
library(ggplot2)
library(data.table)
library(psych)
library(nlme)
library(MuMIn)
library(Rmisc)
library(gridExtra)
library(grid)
library(dplyr)
library(MASS)
library("ggthemes")
library(reshape2)
library(randomForest)
library("glmnet")

if(!dir.exists("plots")) dir.create("plots")

# FUNCTIONS
remove_outliers <- function(x, na.rm = TRUE, ...) {
  qnt <- quantile(x, probs=c(.25, .75), na.rm = na.rm, ...)
  H <- 1.5 * IQR(x, na.rm = na.rm)
  y <- x
  y[x < (qnt[1] - H)] <- NA
  y[x > (qnt[2] + H)] <- NA
  y
}

# Path to the directory with data
dir = "../SECURE_data/"

###################
#### READ DATA ####
###################

#iPOP wearables/clinical combined data
# wear <- read.csv(paste0(dir, "Basis2016_Cleaned_NotNorm0824_WeekPrior.csv"),
#                  header=TRUE,sep=',',stringsAsFactors=FALSE) # for Lukasz script
# do not use:  wear <- read.csv("/Users/jessilyn/Documents/Career_Development/Mentoring/RyanRunge/20170803_FINAL_LASSOS/Basis2016_Norm0824_WeekPrior.csv",
#                  header=TRUE,sep=',',stringsAsFactors=FALSE) # for other figures, may need to resurrect this one
timespans <-c("AllData",
              "MonthPrior",
              "2WeekPrior",
              "WeekPrior",
              "5DayPrior",
              "3DayPrior",
              "DayPrior" )

wear <- read.csv(paste0("/Users/jessilyn/Desktop/framework_paper/Ryan_Runge_Framework_Paper_All_Materials/Output_Tables_from_All_Lassos/Basis_Timespan_Subset_Tables_for_Lassos/", 
                        "Basis2016_Clean_Norm_", timespans[7], "_20180420.csv"),
                 header=TRUE,sep=',',stringsAsFactors=FALSE)

# iPOP vitals (called vitals in Lukasz script)
setwd("/Users/jessilyn/Desktop/framework_paper/weartals")
iPOPvitals <- read.csv(paste0(dir, "vitals.csv"),
                       header=TRUE,sep=',',stringsAsFactors=FALSE)

#iPOP Labs (called labs in Lukasz script)
iPOPlabs <- read.csv(
  paste0(dir, "lab_results_20170717.csv"),
  header=TRUE,sep=',',stringsAsFactors=FALSE)

# 30k vitals
vitals <- fread(paste0(dir, "all_vitals.csv"),
                header=TRUE,sep=',',stringsAsFactors=FALSE)
vitals <- data.frame(vitals)
# 30k labs
labs <- fread(paste0(dir, "all_labs.csv"),
              header=TRUE,sep=',',stringsAsFactors=FALSE)
# 30K labs/vitals combined file <- generated by 20170908_thirtyk.R or 20180412_thirtyk.R (where new vitals like BP and respiration are added in)
# corDf <- read.csv(paste0(dir, "20170905_Cleaned_joined_30k_labs_vitals.csv"),
#                    header=TRUE,sep=',',stringsAsFactors=FALSE)
corDf <- read.csv(paste0(dir, "20180412_Cleaned_joined_30k_labs_ALLvitals.csv"),
                  header=TRUE,sep=',',stringsAsFactors=FALSE)

#iPOP demographics
iPOPdemographics <- read.csv(paste0(dir, "SECURE_ClinWearDemo_SamplePop.csv"),
                             header=TRUE,sep=',',stringsAsFactors=FALSE)

#thirtyK demographics
thirtyKdemog <- read.csv(paste0(dir, "SECURE_20180412_thirtyKDemog.csv"),
                         header=TRUE,sep=',',stringsAsFactors=FALSE)

# names of top clinical tests that will be used for the downstream analyses
top.names<-top.names<-c("LYM", "NEUT", "LYMAB", "NEUTAB", "IGM", "HSCRP", "ALKP", "ALT", "HDL", "MCV", "TBIL", "CHOLHDL", "GLOB", "AG", "CO2", "CA", "LDLHDL", "BUN", "NHDL", "NA.", "UALB", "MONOAB", "CHOL", "MONO", "RDW", "HCT", "TP", "TGL", "EOS", "LDL", "GLU", "AST", "PLT", "K", "EOSAB", "BASOAB", "MCH", "ALB", "HGB", "A1C", "CL", "RBC", "BASO", "MCHC") # names of lab tests from the 30k simple bivariate models

###################
### CLEAN DATA ####
###################

### clean iPOP Vitals ###
names(iPOPvitals)[which(names(iPOPvitals)=="HIMCID")] <- "iPOP_ID"
names(iPOPvitals)[which(names(iPOPvitals)=="RECORDED_TIME")] <- "Clin_Result_Date"
names(iPOPvitals)[which(names(iPOPvitals)=="X.Pulse.")] <- "Pulse"
names(iPOPvitals)[which(names(iPOPvitals)=="X.Temp.")] <- "Temp"
names(iPOPvitals)[which(names(iPOPvitals)=="X.BP.")] <- "BP"
names(iPOPvitals)[which(names(iPOPvitals)=="X.Bmi.")] <- "BMI"

for (i in 1:length(iPOPvitals$BP)){
  iPOPvitals$systolic[i] <- strsplit(as.character(iPOPvitals$BP),'/')[[i]][1]
  iPOPvitals$diastolic[i] <- strsplit(as.character(iPOPvitals$BP),'/')[[i]][2]
}

#Reformat dates
iPOPvitals$Clin_Result_Date <- format(
  as.Date(iPOPvitals$Clin_Result_Date, "%d-%b-%Y"), "%Y-%m-%d")

#Make correlation variables numeric
iPOPvitals[,c("Pulse","Temp","BP","BMI","systolic", "diastolic")] <- apply(
  iPOPvitals[,c("Pulse","Temp","BP","BMI","systolic", "diastolic")], 2,
  function(x) as.numeric(as.character(x)))

#### CLEAN iPOP LABS DATA ####

#Rename columns
names(iPOPlabs)[which(names(iPOPlabs)=="HIMC_ID")] <- "iPOP_ID"
names(iPOPlabs)[which(names(iPOPlabs)=="RESULT_TIME")] <- "Clin_Result_Date"

#Reformat dates
iPOPlabs$Clin_Result_Date <- format(
  as.Date(iPOPlabs$Clin_Result_Date, "%d-%b-%Y"), "%Y-%m-%d")

# allClin <- c("A1C","AG","ALB","ALCRU","ALKP","ALT","AST","BASO",
#              "BASOAB","BUN","CA","CHOL","CHOLHDL","CL","CO2",
#              "CR","EGFR","EOS","EOSAB","ESR","GLOB","GLU","HCT","HDL",
#              "HGB","HSCRP","IGM","K","LDL","LDLHDL","LYM","LYMAB",
#              "MCH","MCHC","MCV","MONO","MONOAB","NA.","NEUT",
#              "NEUTAB","NHDL","PLT", "RBC","RDW","TBIL","TGL","TP","UALB","UALBCR","WBC") 

allClin <- c("ALKP", "LYM", "HSCRP", "ALT", "NEUT", "TBIL", "IGM", "TGL", "MCV", "MCH", "CO2", "LYMAB", "NEUTAB", "UALB", "CHOL", "MONOAB", "ALB", "NA.", "HDL", "PLT", "AG", "HGB", "EOS", "CL", "BUN", "GLOB", "CA", "CHOLHDL", "HCT", "BASOAB", "A1C", "GLU", "LDLHDL", "TP", "EOSAB", "K", "NHDL", "RBC", "MONO", "AST", "MCHC", "RDW", "BASO", "LDL")

for(i in 1:length(allClin)){ #this removes non-numeric characters
  cache <- iPOPlabs[,c(allClin[i])]
  cache <- gsub("[^0-9.]","",cache) #this keeps decimals
  iPOPlabs[,c(allClin[i])] <- cache
}
#Make correlation variables numeric
iPOPlabs[,c(allClin)] <- apply(
  iPOPlabs[,c(allClin)], 2,
  function(x) as.numeric(as.character(x)))

#subset by allClin
iPOPlabs <- iPOPlabs[names(iPOPlabs) %in% c("iPOP_ID","Clin_Result_Date",allClin)]

#Merge data
iPOPcorDf <- merge(iPOPlabs,
                   iPOPvitals[,c("iPOP_ID","Clin_Result_Date",
                                 "Pulse","Temp","BMI","systolic","diastolic")],
                   by=c("iPOP_ID","Clin_Result_Date"))

### clean iPOPcorDf ###
iPOPcorDf[, -c(1,2)] <- apply(iPOPcorDf[, -c(1,2)], 2, remove_outliers)

### clean corDf ### 
corDf[, -c(1,2)] <- apply(corDf[, -c(1,2)], 2, remove_outliers) 

### clean wear ### messes up code for Fig 2C so edited it out, but might be necessary for the CCA in Fig 2E
# wear2<-wear
# wear[,-c(1:6)] <- sapply(wear[,-c(1:6)], as.numeric)
# wear[,-c(1:6)] <- apply(wear[,-c(1:6)], 2, remove_outliers) 

## merge iPOP and demographics
iPOPcorDf.demo <- merge(iPOPcorDf, iPOPdemographics[1:4], by="iPOP_ID")


#30 K Univariate Correlation Fit Plots by Lukasz/Jessie
vitalVars <- which(names(corDf) %in% c("Pulse","Temp"))
clinVars <- which(names(corDf) %in% allClin)

clin.WBCs<- c("NEUT", "LYM", "BASO","MONO","EOS",
              "NEUTAB", "LYMAB", "BASOAB","MONOAB","EOSAB") 
summary.pulse<-list()
summary.Temp<-list()
r.squared <-c()
plots <- list()
idx=0
for (j in clin.WBCs){
  idx=idx+1
  ## 30k All data scatterplots for Fig 3D and 3E
  #pname <- paste0("Plot-",i)
  p<-ggplot(
            #corDf, aes_string(y = corDf[[j]], x = corDf$Pulse)) +
            corDf, aes_string(y = corDf[[j]], x = corDf$Temp)) +
            stat_density_2d(aes(fill = ..level..), geom = 'polygon') +
            #scale_fill_viridis_c(name = "density") +
            geom_point(shape = '.') +
            stat_smooth(method = "lm", formula = y ~ x + I(x^2), size = 1.5, col="darkblue") +
            theme(axis.title=element_text(face="bold",size="14"),axis.text=element_text(size=16,face="bold"), panel.background = element_blank(), axis.line = element_line(colour = "black"))+
            ylab(paste0(c(j ," Bin")))+
            xlab("cTemp")
  #ggsave(paste0(pname,".png"),p)
  plots[[idx]] = p   
}

p <- grid.arrange(grobs=plots,ncol=5)

plots1 <- list()
plots2 <- list()
idx=0
for (j in clin.WBCs){
  idx=idx+1
  corDf$bin2<-ntile(corDf[[j]], 40)
  # for Temp - point plot of bin values (looks like line of points)
  # corDf2 <- summarySE(corDf, measurevar="Temp", groupvars="bin2", na.rm=TRUE)
  # p1<- ggplot(corDf2, aes(x=bin2, y=Temp)) +
  #   geom_point(stat="identity", fill="darkblue") +
  #   geom_errorbar(aes(ymin=Temp-se, ymax=Temp+se), width=.4) +
  #   xlab(paste(c(j, "bins", sep=" ")))+
  #   scale_y_continuous(limits = c(97,99))+
  #   theme(text = element_text(size=9),
  #         axis.text.x = element_text(angle = 60, hjust = 1))
  # # For Pulse
  corDf2 <- summarySE(corDf, measurevar="Pulse", groupvars="bin2", na.rm=TRUE)
  # barplot of bin values (looks like the line of points but with bars instead)
  # p1 <- ggplot(corDf2, aes(x=bin2, y=Pulse)) +
  #   geom_bar(stat="identity", fill="darkred") +
  #   geom_errorbar(aes(ymin=Pulse-se, ymax=Pulse+se), width=.2) +
  #   xlab(paste(c(j, "bins", sep=" "))) +
  #   theme(text = element_text(size=9),
  #         axis.text.x = element_text(angle = 60, hjust = 1))
  # print(paste0(j, ": number of data points in bin = ", sum(corDf$bin2 %in% "2")))
  # quadratic models of bins
  model <-lm(corDf2$Pulse  ~ corDf2$bin2 + I((corDf2$bin2)^2))
  p1 <- ggplot(corDf2, aes(x = bin2, y = Pulse)) +
          stat_smooth(method = "lm", formula = y ~ x + I(x^2), size = 1.5, col="darkred") +
          theme(axis.title=element_text(face="bold",size="14"),axis.text=element_text(size=16,face="bold"), panel.background = element_blank(), axis.line = element_line(colour = "black"))+
          #geom_point(col="black") +
          xlab(paste0(c(j ," Bin")))
  # summary.pulse <- summary(lm(corDf2$Pulse ~ corDf2$bin2 + I(corDf2$bin2^2)))
  # r.squared[j] <- summary.pulse$adj.r.squared
  corDf2 <- summarySE(corDf, measurevar="Temp", groupvars="bin2", na.rm=TRUE)
  p2<-ggplot(corDf2, aes(x = bin2, y = Temp)) +
          stat_smooth(method = "lm", formula = y ~ x + I(x^2), size = 1.5, col="darkblue") +
          #geom_point(col="black") +
          #ylim(c(96,98.5))+
          theme(axis.title=element_text(face="bold",size="14"),axis.text=element_text(size=16,face="bold"), panel.background = element_blank(), axis.line = element_line(colour = "black"))+
          xlab(paste0(c(j ," Bin")))
  # # summary.Temp <- summary(lm(corDf2$Temp ~ corDf2$bin2 + I(corDf2$bin2^2)))
  # # r.squared[j] <- summary.Temp$adj.r.squared
  plots1[[idx]] = p1
  plots2[[idx]] = p2
}
p <- grid.arrange(grobs=plots1,ncol=5)
p2 <- grid.arrange(grobs=plots2,ncol=5)
as.matrix(r.squared)
